image: java:8

before_script:
  - chmod +x ./gradlew

build:
  stage: build
  script:
    - ./gradlew build

maven-publish:
  stage: build
  script:
    - ./gradlew publish
  artifacts:
    paths:
      - build/libs/*.jar

stages:
  - build
  - deploy
