image: java:8

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

before_script:
  - chmod +x ./gradlew

build:
  stage: build
  script:
    - ./gradlew bintrayUpload
  artifacts:
    paths:
      - build/libs/*.jar

stages:
  - build
